import json
import time

from fastapi import HTTPException
from app.utils.json_cleaner import extract_json, try_repair_truncated

from app.prompts.backend_prompt import build_backend_prompt
from app.models.backend_models import BackendPlan
from app.providers.ai_provider import generate_content


def generate_backend(
    architecture,
    provider="auto",
    max_tokens=32000
):
    try:

        print("\n=== START BACKEND ===")

        start = time.time()

        prompt = build_backend_prompt(
            architecture
        )

        text = generate_content(
            prompt,
            provider,
            max_tokens=max_tokens
        )

        if not text:
            raise HTTPException(
                status_code=500,
                detail="Backend LLM returned empty response (token limit likely exceeded)."
            )

        print(
            f"Backend Response Length: {len(text)}"
        )

        print(
            f"Backend Time: {time.time() - start:.2f}s"
        )

        with open(
            "backend_response.txt",
            "w",
            encoding="utf-8"
        ) as f:
            f.write(text)

        clean_text = text
        clean_text = clean_text.replace("```json", "")
        clean_text = clean_text.replace("```", "")
        clean_text = clean_text.strip()

        # Fallback provider order for backend retries — if primary truncates, try next.
        # Cerebras is first because it's the only provider with enough token budget.
        # Reasoning token usage is non-deterministic — retrying Cerebras often succeeds.
        _fallback_providers = ["cerebras", "groq", "openrouter", "gemini"]
        _fallback_idx = 0

        _max_attempts = len(_fallback_providers) + 1
        data = None
        for attempt in range(_max_attempts):
            try:
                data = extract_json(clean_text)
                break
            except (json.JSONDecodeError, ValueError) as e:
                print(f"\n=== BACKEND JSON ERROR (attempt {attempt+1}/{_max_attempts}) ===")
                print(e)

                # If error position is near the end it's likely truncation
                error_pos = getattr(e, 'pos', None) or 0
                is_truncated = error_pos >= len(clean_text) * 0.7

                # On first truncation attempt, try salvage repair before retrying
                if is_truncated and attempt == 0:
                    repaired = try_repair_truncated(clean_text)
                    if repaired and len(repaired.get("files", [])) >= 3:
                        print(
                            f"[TRUNCATION REPAIR] Using salvaged "
                            f"{len(repaired['files'])} file(s) — "
                            f"missing files will be generated by fix agent"
                        )
                        data = repaired
                        break

                if attempt < _max_attempts - 1:
                    if _fallback_idx < len(_fallback_providers):
                        retry_provider = _fallback_providers[_fallback_idx]
                        _fallback_idx += 1
                    else:
                        retry_provider = provider
                    reason = "Truncation detected" if is_truncated else "JSON parse error"
                    print(f"{reason} — retrying with {retry_provider}...")
                    # Groq: limit tokens AND input — the prompt itself is often too large
                    # Use a hard cap well below the 12K TPM limit
                    fallback_tokens = 8000 if retry_provider == "groq" else max_tokens
                    try:
                        text = generate_content(prompt, retry_provider, max_tokens=fallback_tokens)
                    except Exception as fe:
                        print(f"  fallback {retry_provider} failed: {fe} — trying next")
                        # Try repair of what we already have before the next retry
                        if is_truncated:
                            repaired = try_repair_truncated(clean_text)
                            if repaired and len(repaired.get("files", [])) >= 3:
                                print(f"  immediately trying repair ({len(repaired['files'])} files)...")
                                data = repaired
                                break
                        text = None
                    if not text:
                        continue  # try next fallback on next attempt
                    clean_text = text.replace("```json", "").replace("```", "").strip()
                else:
                    # Final attempt: try repair one last time before giving up
                    repaired = try_repair_truncated(clean_text)
                    if repaired and len(repaired.get("files", [])) >= 3:
                        print(f"[TRUNCATION REPAIR] Final salvage: {len(repaired['files'])} files")
                        data = repaired
                        break
                    print("\nBackend Response Preview:")
                    print(clean_text[:500])
                    with open("backend_failed_response.txt", "w", encoding="utf-8") as f:
                        f.write(clean_text)
                    raise HTTPException(status_code=500, detail="Backend returned invalid JSON after all attempts.")

        if not isinstance(data, dict):
            raise HTTPException(
                status_code=500,
                detail="Backend response is not a JSON object."
            )

        if "files" not in data:
            raise HTTPException(
                status_code=500,
                detail="Backend response missing 'files' field."
            )

        if not isinstance(data["files"], list):
            raise HTTPException(
                status_code=500,
                detail="'files' must be a list."
            )

        good_files = []

        for file in data["files"]:

            if not isinstance(file, dict):
                print(f"Skipping invalid file entry (not a dict): {file}")
                continue

            if "path" not in file or "content" not in file:
                print(f"Skipping file entry missing path/content: {file}")
                continue

            path = file["path"].strip()

            path = path.replace(
                "__init__.igma py",
                "__init__.py"
            )

            path = path.replace(
                "__init__.igma",
                "__init__.py"
            )

            file["path"] = path
            content = file["content"]

            if (
                path.endswith(".py")
                and "__init__.py" not in path
                and not content.strip()
            ):
                print(
                    f"Skipping empty generated file: {path} "
                    f"(validation/Missing File Agent will fill this in)"
                )
                continue

            if any(ord(c) > 127 for c in path):
                print(f"Skipping file with invalid (non-ASCII) path: {path}")
                continue

            if not (path.endswith(".py") or path.endswith(".txt")):

                with open(
                    "backend_invalid_paths.txt",
                    "a",
                    encoding="utf-8"
                ) as f:
                    f.write(f"{path}\n")

                print(f"Skipping file with invalid extension: {path}")
                continue

            good_files.append(file)

        if not good_files:
            raise HTTPException(
                status_code=500,
                detail="Backend generated no valid files."
            )

        data["files"] = good_files

        validated = BackendPlan(**data)

        print(
            "=== END BACKEND ==="
        )

        return validated.model_dump()

    except HTTPException:
        raise

    except Exception as e:
        print("BACKEND ERROR:", e)
        raise HTTPException(
            status_code=500,
            detail=(
                f"ForgeAI backend generation failed: {str(e)}"
            )
        )