"""
V14 GitHub Service

Creates a GitHub repo and pushes the generated project code to it.
Requires GITHUB_TOKEN in backend/.env (a Personal Access Token with repo scope).

Flow:
  1. GET /repos/{owner}/{repo} — check if repo exists
  2. POST /user/repos — create repo if not found
  3. git init → git remote add → git push (via subprocess)

The repo name is derived from the project name (kebab-case).
"""
import json
import os
import subprocess
import time
from pathlib import Path

import requests


GITHUB_API = "https://api.github.com"


def _get_token() -> str | None:
    return os.getenv("GITHUB_TOKEN")


def _get_username(token: str) -> str | None:
    resp = requests.get(
        f"{GITHUB_API}/user",
        headers={"Authorization": f"token {token}", "Accept": "application/vnd.github+json"},
        timeout=15,
    )
    if resp.ok:
        return resp.json().get("login")
    return None


def _repo_exists(token: str, owner: str, repo: str) -> bool:
    resp = requests.get(
        f"{GITHUB_API}/repos/{owner}/{repo}",
        headers={"Authorization": f"token {token}", "Accept": "application/vnd.github+json"},
        timeout=15,
    )
    return resp.status_code == 200


def _create_repo(token: str, name: str, description: str = "") -> dict | None:
    resp = requests.post(
        f"{GITHUB_API}/user/repos",
        headers={"Authorization": f"token {token}", "Accept": "application/vnd.github+json"},
        json={"name": name, "description": description, "private": False, "auto_init": False},
        timeout=30,
    )
    if resp.ok:
        return resp.json()
    return None


def _run(cmd: list[str], cwd: str, env: dict | None = None) -> tuple[int, str]:
    result = subprocess.run(
        cmd, cwd=cwd, capture_output=True, text=True,
        env={**os.environ, **(env or {})},
        timeout=120,
    )
    return result.returncode, (result.stdout + result.stderr).strip()


def push_to_github(
    project_path: str,
    project_name: str,
    description: str = "",
) -> dict:
    """
    Create (or reuse) a GitHub repo and push the project code.

    Returns:
        {
            "success": bool,
            "repo_url": str | None,     # https://github.com/owner/repo
            "clone_url": str | None,    # https://github.com/owner/repo.git
            "error": str | None,
        }
    """
    token = _get_token()
    if not token:
        return {"success": False, "repo_url": None, "clone_url": None,
                "error": "GITHUB_TOKEN not set in .env — cannot push to GitHub"}

    slug = project_name.lower().replace("_", "-").replace(" ", "-")

    # Get GitHub username
    owner = _get_username(token)
    if not owner:
        return {"success": False, "repo_url": None, "clone_url": None,
                "error": "Could not get GitHub username — check GITHUB_TOKEN permissions"}

    # Create repo if it doesn't exist
    if not _repo_exists(token, owner, slug):
        print(f"  [GitHub] Creating repo {owner}/{slug}...")
        repo_data = _create_repo(token, slug, description or f"Generated by ForgeAI: {project_name}")
        if not repo_data:
            return {"success": False, "repo_url": None, "clone_url": None,
                    "error": f"Failed to create GitHub repo {owner}/{slug}"}
        time.sleep(2)  # Let GitHub settle
    else:
        print(f"  [GitHub] Repo {owner}/{slug} already exists — pushing to it")

    repo_url = f"https://github.com/{owner}/{slug}"
    clone_url = f"https://{token}@github.com/{owner}/{slug}.git"

    cwd = str(project_path)

    # Initialize git if not already
    if not (Path(project_path) / ".git").exists():
        rc, out = _run(["git", "init", "-b", "main"], cwd)
        if rc != 0:
            # Older git doesn't support -b, try without
            _run(["git", "init"], cwd)
            _run(["git", "checkout", "-b", "main"], cwd)
        print(f"  [GitHub] git init: {out[:100]}")

    # Write a .gitignore so we don't push junk
    gitignore_path = Path(project_path) / ".gitignore"
    if not gitignore_path.exists():
        gitignore_path.write_text(
            "__pycache__/\n*.pyc\n*.pyo\n.env\n*.db\n*.sqlite3\nvenv/\n.venv/\n"
            "node_modules/\ndist/\n.railway/\nfix_logs.json\nmetadata.json\n"
        )

    # Configure git identity (needed in CI environments)
    _run(["git", "config", "user.email", "forgeai@example.com"], cwd)
    _run(["git", "config", "user.name", "ForgeAI"], cwd)

    # Stage all files
    rc, out = _run(["git", "add", "-A"], cwd)
    print(f"  [GitHub] git add: rc={rc}")

    # Commit
    rc, out = _run(["git", "commit", "--allow-empty", "-m", "feat: initial commit by ForgeAI"], cwd)
    print(f"  [GitHub] git commit: {out[:150]}")

    # Set remote (replace if exists)
    _run(["git", "remote", "remove", "origin"], cwd)
    _run(["git", "remote", "add", "origin", clone_url], cwd)

    # Push
    print(f"  [GitHub] Pushing to {repo_url}...")
    rc, out = _run(["git", "push", "-u", "origin", "main", "--force"], cwd)
    if rc != 0:
        # Try pushing as master
        rc2, out2 = _run(["git", "push", "-u", "origin", "HEAD:main", "--force"], cwd)
        if rc2 != 0:
            return {"success": False, "repo_url": repo_url, "clone_url": clone_url,
                    "error": f"git push failed: {out}\n{out2}"}

    print(f"  [GitHub] Pushed: {repo_url}")
    return {
        "success": True,
        "repo_url": repo_url,
        "clone_url": f"https://github.com/{owner}/{slug}.git",  # safe URL without token
        "owner": owner,
        "repo": slug,
        "error": None,
    }
