"""
Vercel deployment provider — uses Vercel REST API directly (no CLI dependency,
same style as render_provider.py).

Requires:
  - VERCEL_TOKEN in backend/.env (vercel.com → Account Settings → Tokens)

Deploys ONE Vercel project per generated app, containing both:
  - The built React frontend (static files, served at "/")
  - The FastAPI backend, wrapped in api/index.py as a Python serverless
    function and mounted under "/api" so it can share one Vercel project
    with the static frontend without route collisions (see _API_WRAPPER).

Flow:
  1. npm install && npm run build (same isolated /tmp build as Cloudflare)
  2. Patch the built frontend's API base URL to the relative "/api" path
     (same-origin — no separate backend domain like Render+Cloudflare uses)
  3. Write api/index.py (ASGI wrapper mounting the generated app under /api),
     a root requirements.txt (copied from app/requirements.txt), and
     vercel.json (routes /api/* to the function, everything else falls
     through to the static build for SPA routing)
  4. Upload every file's content via the Vercel file-upload endpoint
     (dedups by SHA1 digest), then create a deployment referencing them
  5. Poll the deployment until READY, return the live *.vercel.app URL
"""
import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import time
from pathlib import Path

import requests

from app.deployments.base_provider import BaseDeploymentProvider, DeploymentResult

VERCEL_API = "https://api.vercel.com"


def _npm() -> str:
    found = shutil.which("npm")
    if found:
        return found
    if os.name == "nt":
        for candidate in ("npm.cmd", "npm.bat"):
            found = shutil.which(candidate)
            if found:
                return found
    return "npm"


def _slug(name: str) -> str:
    slug = re.sub(r"[^a-z0-9-]", "-", name.lower().replace("_", "-")).strip("-")
    return slug[:52] or "forge-app"


_API_WRAPPER = '''"""Auto-generated by ForgeAI's Vercel provider.
Mounts the generated FastAPI app under /api so one Vercel project can
serve the static frontend and the backend from the same origin."""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from fastapi import FastAPI

from app.main import app as _generated_app

app = FastAPI()
app.mount("/api", _generated_app)
'''

def _patch_api_base_url(text: str) -> str:
    """Rewrite src/api.js's axios baseURL to the relative '/api' path for a
    same-origin Vercel deploy. Must match not just a bare string literal
    (`baseURL: ''`) but also the `import.meta.env.VITE_API_URL || '<fallback>'`
    expression the frontend generation prompt actually produces -- a plain
    `['\"][^'\"]*['\"]` match right after the colon misses that case entirely,
    leaving the fallback (often 'http://localhost:8000') baked into the
    production bundle.
    """
    return re.sub(
        r"baseURL\s*:\s*(?:import\.meta\.env\.\w+\s*\|\|\s*)?['\"][^'\"]*['\"]",
        "baseURL: '/api'",
        text,
    )


def _build_vercel_json(dist_dir: Path) -> dict:
    """
    Legacy `builds`+`routes` config (paired with the raw-file-upload
    deployments API) only builds what's explicitly listed — unlike a
    git-connected deploy, it does NOT implicitly add a static builder for
    leftover files. Every top-level entry actually present in dist/ must be
    declared or Vercel serves the Python function fine but 404s everything
    else (confirmed: an api-only builds array left dist/'s files sitting in
    the build's `src/` stage and never copied into the served `out/`).
    """
    static_builds = []
    for child in sorted(dist_dir.iterdir()):
        if child.is_dir():
            static_builds.append({"src": f"{child.name}/**", "use": "@vercel/static"})
        else:
            static_builds.append({"src": child.name, "use": "@vercel/static"})

    return {
        "version": 2,
        "builds": [
            {"src": "api/index.py", "use": "@vercel/python"},
            *static_builds,
        ],
        "routes": [
            {"src": "/api/(.*)", "dest": "api/index.py"},
            {"handle": "filesystem"},
            {"src": "/(.*)", "dest": "/index.html"},
        ],
    }


class VercelProvider(BaseDeploymentProvider):
    """Deploy both frontend and backend of a generated project to one Vercel project."""

    def __init__(self) -> None:
        self.token = os.getenv("VERCEL_TOKEN")
        self.team_id = os.getenv("VERCEL_TEAM_ID")  # optional, for team accounts

    def _check(self) -> str | None:
        if not self.token:
            return "VERCEL_TOKEN not set in .env — get it from vercel.com → Account Settings → Tokens"
        return None

    def _headers(self) -> dict:
        return {"Authorization": f"Bearer {self.token}"}

    def _qs(self) -> dict:
        return {"teamId": self.team_id} if self.team_id else {}

    def _run(self, cmd: list[str], cwd: str, env: dict) -> subprocess.CompletedProcess:
        from app.utils.proc import run_tree_capped
        result = run_tree_capped(cmd, cwd=cwd, timeout=300, env=env, text=False)
        stdout = (result.stdout or b"").decode("utf-8", errors="replace")
        stderr = (result.stderr or b"").decode("utf-8", errors="replace")
        return subprocess.CompletedProcess(result.args, result.returncode, stdout, stderr)

    def _prepare_build_dir(self, project_path: str, slug: str) -> Path:
        """Copy the whole project (frontend + backend) into an isolated /tmp dir."""
        _EXCLUDE = {"node_modules", "dist", ".git", ".env", "venv", ".venv", "__pycache__"}
        tmp = Path(tempfile.mkdtemp(prefix=f"forge-vc-{slug[:20]}-"))
        for item in Path(project_path).iterdir():
            if item.name in _EXCLUDE:
                continue
            dst = tmp / item.name
            try:
                if item.is_dir():
                    shutil.copytree(
                        str(item), str(dst),
                        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo"),
                    )
                else:
                    shutil.copy2(str(item), str(dst))
            except Exception as copy_err:
                print(f"  [Vercel] Warning: skipped {item.name}: {copy_err}")
        return tmp

    def deploy(
        self,
        project_path: str,
        project_name: str,
        env_vars: dict | None = None,
    ) -> DeploymentResult:
        err = self._check()
        if err:
            return DeploymentResult(success=False, url=None, logs="", error=err,
                                    deploy_id=None, provider="vercel")

        slug = _slug(project_name)
        logs: list[str] = []
        build_dir: Path | None = None
        # DATABASE_URL (provisioned by NeonProvider upstream) and any other
        # generated-app env vars flow through to the serverless function via
        # the deployment's `env` field — Vercel functions have no disk, so
        # this MUST be a real external Postgres, never sqlite.
        deploy_env = dict(env_vars or {})

        try:
            build_env = {k: v for k, v in os.environ.items() if k != "CI"}
            npm_cache = str(Path(tempfile.gettempdir()) / ".npm-forge-cache")
            build_env["npm_config_cache"] = npm_cache
            # Force devDependencies to install regardless of the ForgeAI
            # server's own NODE_ENV -- see cloudflare_provider.py's identical
            # fix for the full incident (production Render deploy, 2026-07-16).
            build_env["NODE_ENV"] = "development"
            # Cap Node's heap -- see cloudflare_provider.py's identical fix
            # for the full incident (a vite build OOM-killed and auto-
            # restarted ForgeAI's own 512MB Render instance, 2026-07-17).
            heap_mb = os.environ.get("FORGE_FRONTEND_BUILD_HEAP_MB", "400")
            build_env["NODE_OPTIONS"] = (build_env.get("NODE_OPTIONS", "") + f" --max-old-space-size={heap_mb}").strip()

            package_json = Path(project_path) / "package.json"
            if not package_json.exists():
                return DeploymentResult(
                    success=False, url=None, logs="",
                    error="No package.json found — frontend not generated",
                    deploy_id=None, provider="vercel",
                )

            npm = _npm()
            if npm == "npm" and not shutil.which("npm"):
                return DeploymentResult(
                    success=False, url=None, logs="",
                    error="npm not found — install Node.js to enable frontend deployment",
                    deploy_id=None, provider="vercel",
                )

            build_dir = self._prepare_build_dir(project_path, slug)
            cwd = str(build_dir)

            print(f"  [Vercel] Source:    {project_path}")
            print(f"  [Vercel] Build dir: {build_dir}")

            # Same-origin deploy — the frontend calls its own backend at /api,
            # not a separate domain like the Render+Cloudflare split does.
            _api_candidates = list(build_dir.rglob("src/api.js")) + list(build_dir.rglob("src/api.jsx"))
            print(f"  [Vercel] api client search found {len(_api_candidates)} file(s): {[str(p.relative_to(build_dir)) for p in _api_candidates]}")
            for api_file in _api_candidates:
                try:
                    text = api_file.read_text(encoding="utf-8")
                    patched = _patch_api_base_url(text)
                    if patched != text:
                        api_file.write_text(patched, encoding="utf-8")
                        print(f"  [Vercel] Patched {api_file.name}: baseURL → '/api'")
                    else:
                        print(f"  [Vercel] {api_file.name} did not need patching (no baseURL match, or already '/api')")
                except Exception as patch_err:
                    print(f"  [Vercel] Warning: could not patch {api_file}: {patch_err}")

            print("  [Vercel] Running npm install...")
            install_result = self._run(
                [npm, "install", "--no-fund", "--no-audit", "--legacy-peer-deps"],
                cwd, build_env,
            )
            logs.append(f"[npm install]\n{install_result.stdout[-1000:]}\n{install_result.stderr[-500:]}")
            if install_result.returncode != 0:
                return DeploymentResult(
                    success=False, url=None, logs="\n".join(logs),
                    error=f"npm install failed (rc={install_result.returncode}):\n{install_result.stderr[-800:]}",
                    deploy_id=None, provider="vercel",
                )

            build_result = self._run([npm, "run", "build"], cwd, build_env)
            logs.append(f"[npm build]\n{build_result.stdout[-500:]}\n{build_result.stderr[-300:]}")
            if build_result.returncode != 0:
                combined_err = ((build_result.stdout or "") + "\n" + (build_result.stderr or "")).strip()
                return DeploymentResult(
                    success=False, url=None, logs="\n".join(logs),
                    error=f"Frontend build failed: {combined_err[-1200:]}",
                    deploy_id=None, provider="vercel",
                )

            dist_dir = build_dir / "dist"
            if not dist_dir.exists():
                return DeploymentResult(
                    success=False, url=None, logs="\n".join(logs),
                    error="dist/ not found after build",
                    deploy_id=None, provider="vercel",
                )

            # Backend: wrap the generated FastAPI app for Vercel's Python runtime.
            app_dir = build_dir / "app"
            if not app_dir.exists():
                return DeploymentResult(
                    success=False, url=None, logs="\n".join(logs),
                    error="app/ backend package not found — nothing to wrap for Vercel Python runtime",
                    deploy_id=None, provider="vercel",
                )
            api_dir = build_dir / "api"
            api_dir.mkdir(exist_ok=True)
            (api_dir / "index.py").write_text(_API_WRAPPER, encoding="utf-8")

            req_src = app_dir / "requirements.txt"
            req_text = req_src.read_text(encoding="utf-8") if req_src.exists() else "fastapi\nuvicorn\nsqlalchemy\n"
            # Generated requirements.txt is written assuming SQLite (Render's
            # own deploy needs the same fix, but that's a separate pipeline).
            # Since DATABASE_URL here is always a Neon Postgres URL, the app's
            # own eager `Base.metadata.create_all()` at import time needs a
            # real driver or the whole function crashes on cold start.
            db_url = deploy_env.get("DATABASE_URL", "")
            if db_url.startswith("postgres") and "psycopg2" not in req_text and "pg8000" not in req_text:
                req_text = req_text.rstrip() + "\npsycopg2-binary\n"
            (build_dir / "requirements.txt").write_text(req_text, encoding="utf-8")

            vercel_json = _build_vercel_json(dist_dir)
            (build_dir / "vercel.json").write_text(json.dumps(vercel_json, indent=2), encoding="utf-8")

            # ── Collect deployable files: built frontend + api/ + app/ + vercel.json ──
            deploy_files: list[Path] = []
            deploy_files.extend(p for p in dist_dir.rglob("*") if p.is_file())
            deploy_files.extend(p for p in api_dir.rglob("*") if p.is_file())
            deploy_files.extend(p for p in app_dir.rglob("*.py") if p.is_file())
            deploy_files.append(build_dir / "requirements.txt")
            deploy_files.append(build_dir / "vercel.json")

            def rel_name(p: Path) -> str:
                if p.is_relative_to(dist_dir):
                    return str(p.relative_to(dist_dir)).replace(os.sep, "/")
                return str(p.relative_to(build_dir)).replace(os.sep, "/")

            print(f"  [Vercel] Uploading {len(deploy_files)} files...")
            file_refs = []
            for fp in deploy_files:
                data = fp.read_bytes()
                digest = hashlib.sha1(data).hexdigest()
                r = requests.post(
                    f"{VERCEL_API}/v2/files",
                    headers={**self._headers(), "x-vercel-digest": digest, "Content-Type": "application/octet-stream"},
                    params=self._qs(),
                    data=data,
                    timeout=30,
                )
                if not r.ok:
                    logs.append(f"[Vercel] file upload failed for {rel_name(fp)}: {r.status_code} {r.text[:200]}")
                    continue
                file_refs.append({"file": rel_name(fp), "sha": digest, "size": len(data)})

            deploy_payload = {
                "name": slug,
                "files": file_refs,
                "target": "production",
                "projectSettings": {"framework": None},
            }
            if deploy_env:
                deploy_payload["env"] = deploy_env

            print(f"  [Vercel] Creating deployment '{slug}'...")
            r = requests.post(
                f"{VERCEL_API}/v13/deployments",
                headers={**self._headers(), "Content-Type": "application/json"},
                params=self._qs(),
                json=deploy_payload,
                timeout=60,
            )
            if not r.ok:
                return DeploymentResult(
                    success=False, url=None, logs="\n".join(logs),
                    error=f"Vercel deployment create failed: {r.status_code} {r.text[:500]}",
                    deploy_id=None, provider="vercel",
                )
            dep = r.json()
            deploy_id = dep.get("id") or dep.get("uid")
            url = dep.get("url")
            final_url = f"https://{url}" if url and not url.startswith("http") else url

            print(f"  [Vercel] Deployment queued: {final_url} (building...)")
            logs.append(f"[Vercel] deployment {deploy_id} → {final_url}")

            # Team/org accounts on Vercel default new projects to Deployment
            # Protection (an SSO login wall) on every environment including
            # production. Generated apps are meant to be publicly reachable —
            # a wall here would make every deploy look broken to end users.
            self._disable_deployment_protection(slug, logs)

            return DeploymentResult(
                success=bool(final_url),
                url=final_url,
                logs="\n".join(logs),
                error=None,
                deploy_id=deploy_id,
                provider="vercel",
                metadata={
                    "backend_url": f"{final_url}/api" if final_url else None,
                    "frontend_url": final_url,
                },
            )

        except Exception as exc:
            return DeploymentResult(
                success=False, url=None, logs="\n".join(logs),
                error=str(exc), deploy_id=None, provider="vercel",
            )
        finally:
            if build_dir and build_dir.exists():
                shutil.rmtree(str(build_dir), ignore_errors=True)

    def _disable_deployment_protection(self, project_slug: str, logs: list) -> None:
        try:
            r = requests.patch(
                f"{VERCEL_API}/v9/projects/{project_slug}",
                headers={**self._headers(), "Content-Type": "application/json"},
                params=self._qs(),
                json={"ssoProtection": None},
                timeout=15,
            )
            if r.ok:
                print(f"  [Vercel] Disabled deployment protection for '{project_slug}'")
            else:
                logs.append(f"[Vercel] Could not disable deployment protection: {r.status_code} {r.text[:200]}")
        except Exception as exc:
            logs.append(f"[Vercel] Deployment protection call failed: {exc}")

    def get_logs(self, deploy_id: str) -> str:
        if not self.token or not deploy_id:
            return "No token or deploy ID"
        r = requests.get(
            f"{VERCEL_API}/v2/deployments/{deploy_id}/events",
            headers=self._headers(), params=self._qs(), timeout=30,
        )
        return r.text[:2000] if r.ok else f"Could not fetch logs: {r.status_code}"

    def get_status(self, deploy_id: str) -> str:
        if not self.token or not deploy_id:
            return "unknown"
        r = requests.get(
            f"{VERCEL_API}/v13/deployments/{deploy_id}",
            headers=self._headers(), params=self._qs(), timeout=30,
        )
        if r.ok:
            state = r.json().get("readyState", "unknown")
            return {"READY": "live", "ERROR": "failed"}.get(state, state.lower())
        return "unknown"

    def poll_ready(self, deploy_id: str, attempts: int = 30, wait: int = 10) -> bool:
        """Poll until the deployment is READY or ERROR (Vercel builds are usually ~1-2 min)."""
        for i in range(attempts):
            status = self.get_status(deploy_id)
            if status == "live":
                return True
            if status == "failed":
                return False
            time.sleep(wait)
        return False

    def delete(self, deploy_id: str) -> bool:
        if not self.token or not deploy_id:
            return False
        r = requests.delete(
            f"{VERCEL_API}/v13/deployments/{deploy_id}",
            headers=self._headers(), params=self._qs(), timeout=15,
        )
        return r.ok
